Credits slider
jandoubek/pvs-2020-lectures pull request #28
Opened 2020-11-18 21:42 UTC by eskimo-kidnap

Implementace #21

2020-11-19 14:59 UTC, SachCZ requested changes
Je to super, jen dvě drobné věci, které opravíš za pár sekund a to `setValue` - `onChange` a hodit zatím max credits do konstant.

2020-11-19 14:59 UTC, SachCZ commented on data/generate_toy_data.jl
> +using JSON
V budoucnu by bylo ideální aby toto mělo vlastní pull request, aby se to dalo případně mergnout nezávisle.

2020-11-19 14:59 UTC, SachCZ commented on src/CreditsSlider.js
> +const CreditsSlider = ({setValue, value, maxvalue}) => {
byl bych pro držet se konvence `onChange` místo `setValue`. Takto to mají všechny inputy v material ui.

2020-11-19 14:59 UTC, SachCZ commented on src/utility.js
> +const maxcredits = 40;
Chápu, že tu výhledově bude funkce, ale toto bych zatím strčil do constants.js.

2020-11-19 14:59 UTC, SachCZ commented on src/utility.js
> +    return [match[1], match[2]].map(letter => parseInt(letter));
Celkově se mi parseCredits moc líbí. Skvělé řešení!

2020-11-19 14:59 UTC, SachCZ commented on src/ResultsPage.js
> +    subjects = subjects.filter(subject => (subject.credits >= credits[0] && subject.credits <= credits[1]));
:+1:

2020-11-23 16:35 UTC, eskimo-kidnap commented
Done 70fbac30c5381dd9a2ed2ff86aecc075c48821f4

2020-11-23 16:37 UTC, SachCZ approved these changes
Super!

2020-11-23 16:40 UTC, SachCZ commented
Můžes mergnout a deletnout branch. Poté  bych to viděl na nějaké nové issue a branch. Myslím, že tohle je pěkné demo celkové worflow :+1:

2020-11-23 16:43 UTC, merged